kind: pipeline
type: docker
name: Build


platform:
  os: linux
  arch: amd64

steps:

- name: test
  image: alpine
  commands:
    - echo hello world

- name: test2
  image: alpine
  commands:
    - echo hello world
